variables:
  JAVA_DOCKER_IMAGE: "harbor.uni-muenster.de/proxy-docker/eclipse-temurin:21-alpine"
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true


.release_tag: &release-tag
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+/ # describe how your version tags look like!


cache:
  paths:
    - $CI_PROJECT_DIR/.m2/repository

stages:
  - test
  - push


verify:
  stage: test
  image: $JAVA_DOCKER_IMAGE
  script:
    - ./mvnw $MAVEN_CLI_OPTS -Popenapi generate-sources verify


formatting:
  stage: test
  image: $JAVA_DOCKER_IMAGE
  script:
    - ./mvnw $MAVEN_CLI_OPTS spotless:check

push packages:
  stage: push
  image: $JAVA_DOCKER_IMAGE
  script:
    - ./mvnw -Drevision=$CI_COMMIT_REF_NAME -Dchangelist="" $MAVEN_CLI_OPTS clean
    - ./mvnw -Drevision=$CI_COMMIT_REF_NAME -Dchangelist="" $MAVEN_CLI_OPTS -Popenapi generate-sources
    - ./mvnw -Drevision=$CI_COMMIT_REF_NAME -Dchangelist="" $MAVEN_CLI_OPTS -s .gitlab/settings.xml deploy
  rules:
    - !reference [ .release_tag, rules ]

