/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "seed-xc"
include(":resources")
include(":seed-resource-providers")
include(":seed-dts")
include(":seed-xslt-compiler")
include(":seed-xc-sparql")
include(":seed-xc-plugins")
include(":seed-xc-saxon")
include(":seed-xc-api")
include(":seed-xml-transformer")
include(":seed-xc-transformations")
project(":seed-resource-providers").projectDir = file("plugins/resource-providers")
project(":seed-dts").projectDir = file("dts")
project(":seed-xslt-compiler").projectDir = file("compiler")
project(":seed-xc-sparql").projectDir = file("plugins/seed-xc-sparql")
project(":seed-xc-plugins").projectDir = file("plugins")
project(":seed-xc-saxon").projectDir = file("plugins/saxon")
project(":seed-xc-api").projectDir = file("api")
project(":seed-xml-transformer").projectDir = file("transformer")
project(":seed-xc-transformations").projectDir = file("transformations")
