# Location for the saxon configuration file. See
# https://www.saxonica.com/documentation10/#!configuration/configuration-file
de.ulbms.scdh.seed.xc.saxon.ConfiguredProcessor.saxonConfigLocations = ${saxon-config.file}

# Whether URIs without a protocol, i.e. references to the local file
# system are allowed as input to a Saxon transformer. Per default this
# is set to false because allowing them would be a security issue.
de.ulbms.scdh.seed.xc.saxon.harden.ServiceConfiguration.nonProtocolURIsAllowed = false

# Only the file system under this path will be accessible. This is a
# security feature.
de.ulbms.scdh.seed.xc.saxon.harden.FileURIResolver.path = ${file-uri-resolver.path}

# Inside the accessible part of the file system: relative paths will
# be resolved to this. This is important when using transformation config files.
de.ulbms.scdh.seed.xc.saxon.harden.FileURIResolver.baseUri = ${file-uri-resolver.baseUri}

quarkus.log.level = info
quarkus.log.category."de.ulbms.scdh.seed".level = debug

# Use the maven property in the native build profile in service/pom.xml instead!
# quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.hc.client5.http.impl.auth.NTLMEngineImpl


# https://quarkus.io/guides/http-reference#cors-filter
quarkus.http.cors=true
%dev.quarkus.http.cors.origins=/.*/
