# SPARQL for constructing the collection and resource metadata returned by the DTS collection endpoint with nav=children

# The input graph is expected to be prepared DTS collection metadata,
# all collections and resources joined in in graph. See
# text/collection.json for an example.

# USAGE: see test/collection/README.md


PREFIX dts: <https://w3id.org/dts/api#>
PREFIX dct: <http://purl.org/dc/terms/>

CONSTRUCT {
  ?resource ?rp ?ro .
  ?ros ?rop ?roo .

  ?member ?mp ?mo .
  ?mos ?mop ?moo .

  ?resource dts:totalChildren ?resourceChildren .
  ?resource dts:totalParents ?resourceParents .
  ?member dts:totalChildren ?memberChildren .
  ?member dts:totalParents ?memberParents .

}

WHERE {
  #BIND(<http://example.com/general> as ?id ) .
  #BIND(<http://example.com/apocryphs> as ?id ) .
  #BIND(<http://example.com/matt.xml> as ?id ) .

  BIND(?id as ?resource) .     # changed in parametrized query
  BIND(?nav as ?navUnused) .   # changed in parametrized query
  BIND(?page as ?pageUnused) . # changed in parametrized query

  ?resource ?rp ?ro .
  ?resource (!dts:member)* ?ros . # arbitrary prop paths except into members
  ?ros ?rop ?roo .

  OPTIONAL {
    ?resource dts:member? ?member . # nav=children # dts:member? is important!
    ?member ?mp ?mo .
    ?member (!dts:member)* ?mos . # arbitrary prop paths except into members
    ?mos ?mop ?moo .
  }

  FILTER(?mp != dts:member) .
  FILTER(?mop != dts:member) .

  FILTER(?rp != dts:totalChildren) .
  FILTER(?rp != dts:totalParents) .
  FILTER(?mp != dts:totalChildren) .
  FILTER(?mp != dts:totalParents) .

  FILTER(?rop != dts:totalChildren) .
  FILTER(?rop != dts:totalParents) .
  FILTER(?mop != dts:totalChildren) .
  FILTER(?mop != dts:totalParents) .

  OPTIONAL
  {
    SELECT ?resource (COALESCE(COUNT(DISTINCT(?child)), 0) as ?resourceChildrenCalculated)
    WHERE {
      ?resource dts:member ?child .
    }
    GROUP BY ?resource
  }

  OPTIONAL
  {
    SELECT ?resource (COALESCE(COUNT(DISTINCT(?parent)), 0) as ?resourceParentsCalculated)
    WHERE {
      ?parent dts:member ?resource .
    }
    GROUP BY ?resource
  }

  BIND(COALESCE(?resourceChildrenCalculated, 0) as ?resourceChildren) .
  BIND(COALESCE(?resourceParentsCalculated, 0) as ?resourceParents) .

  OPTIONAL
  {
    SELECT ?member (COALESCE(COUNT(?parent), 0) as ?memberParents)
    WHERE {
      ?parent dts:member ?member .
    }
    GROUP BY ?member
  }

  OPTIONAL
  {
    SELECT ?member (COALESCE(COUNT(?child), 0) as ?memberChildren)
    WHERE {
      ?member dts:member ?child .
    }
    GROUP BY ?member
  }

}
