/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":seed-xc-api"))
    testImplementation(project(":seed-resource-providers"))
    testImplementation(libs.io.quarkus.quarkus.junit5)
}

description = "SEED XC  Resource Provider Manager"
