/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":seed-xc-api"))
    api(libs.org.apache.jena.jena.arq.x1)
    api(libs.com.fasterxml.jackson.datatype.jackson.datatype.jakarta.jsonp)
    api(libs.com.apicatalog.titanium.json.ld)
    api(libs.org.slf4j.slf4j.api)
    testImplementation(project(":seed-resource-providers"))
    testImplementation(libs.io.quarkus.quarkus.junit5)
    testImplementation(libs.io.quarkus.quarkus.junit5.mockito)
}

description = "SEED XC SPARQL"
