/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":seed-xc-api"))
    api(project(":seed-xc-saxon"))
    api(libs.io.quarkus.quarkus.rest)
    api(libs.io.quarkus.quarkus.smallrye.openapi) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.jboss.shrinkwrap", "module" to "shrinkwrap-api"))
    }
    api(libs.io.quarkus.quarkus.swagger.ui)
    api(libs.io.quarkus.quarkus.arc)
    api(libs.io.quarkus.quarkus.rest.jackson)
    api(libs.com.saxonica.saxon.ee)
    testImplementation(libs.io.quarkus.quarkus.junit5)
    testImplementation(libs.io.rest.assured.rest.assured) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.activation", "module" to "activation"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "javax.activation", "module" to "javax.activation-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "jakarta.activation", "module" to "jakarta.activation-api"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "com.sun.xml.bind", "module" to "jaxb-osgi"))

        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "commons-logging", "module" to "commons-logging"))
    }
}

description = "SEED XSLT Compilation Service"
