/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":seed-xc-api"))
    api(libs.org.slf4j.slf4j.api)
    api(libs.io.quarkus.quarkus.arc)
    testImplementation(libs.io.quarkus.quarkus.junit5)
}

description = "SEED XC Resource Providers"
