## Container image with DTS Transformations preinstalled.

FROM quay.io/quarkus/ubi9-quarkus-micro-image:2.0
WORKDIR /work/
RUN mkdir -p /work/resources
RUN mkdir -p /work/projects
RUN chown -R 1001 /work \
    && chmod -R "g+rwX" /work \
    && chown -R 1001:root /work
COPY --chown=1001:root --chmod=555 dts/target/*-runner /work/application

COPY  --chown=1001:root dts/target/dependencies/ /work/resources/

USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]