/*
 * This file was generated by the Gradle 'init' task.
 */

dependencies {
    implementation("de.undercouch.download:de.undercouch.download.gradle.plugin:5.7.0")
    implementation("org.openapitools:openapi-generator-gradle-plugin:7.14.0")
    //implementation("org.openapi.generator:7.23.0")
}

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    mavenCentral()
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}
