/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.io.quarkus.quarkus.hibernate.validator)
    api(libs.io.quarkus.quarkus.smallrye.openapi) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.jboss.shrinkwrap", "module" to "shrinkwrap-api"))
    }
    api(libs.io.quarkus.quarkus.rest)
    api(libs.io.quarkus.quarkus.mutiny)
}

description = "SEED XC API"
