/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
    id("de.undercouch.download")
}

dependencies {
    api(libs.io.quarkus.quarkus.hibernate.validator)
    api(libs.io.quarkus.quarkus.smallrye.openapi) {
        // TODO: This exclude was sourced from a POM exclusion and is NOT exactly equivalent, see: https://docs.gradle.org/9.6.1/userguide/build_init_plugin.html#sec:pom_maven_conversion
        exclude(mapOf("group" to "org.jboss.shrinkwrap", "module" to "shrinkwrap-api"))
    }
    api(libs.io.quarkus.quarkus.rest)
    api(libs.io.quarkus.quarkus.mutiny)
}

tasks.register<org.openapitools.generator.gradle.plugin.tasks.GenerateTask>("generate") {
    inputSpec("$rootDir/src/main/resources/openapi/seed-xc-openapi.yaml")
}

tasks.register<de.undercouch.gradle.tasks.download.Download>("download-openapi") {
    src("https://raw.githubusercontent.com/SCDH/dts-openapi/refs/tags/${dts-openapi.version}/standalone/facade-openapi.yaml")
    dest(layout.buildDirectory.dir("openapi"))
    overwrite(false)
}

description = "SEED XC API"
