name: Tests
on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'doc'
      - 'samples'
    pull_request:
      branches:
        - main

jobs:
  
  test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK and configure settings.xml for registries on https://maven.pkg.github.com/scdh/*
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
          server-id: scdh

      - name: get required resources
        run: ./mvnw --batch-mode --update-snapshots -Pdownload-openapi generate-sources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: run maven verify
        run: ./mvnw --batch-mode --update-snapshots verify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
