/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(project(":seed-xc-api"))
    api(libs.net.sf.saxon.saxon.he)
    api(libs.org.xmlresolver.xmlresolver)
    api(libs.org.slf4j.slf4j.api)
    api(libs.xerces.xercesimpl)
    testImplementation(project(":seed-resource-providers"))
    testImplementation(libs.io.quarkus.quarkus.junit5)
    testImplementation(libs.nu.validator.htmlparser)
    testImplementation(libs.org.ccil.cowan.tagsoup.tagsoup)
}

description = "SEED XC Saxon"
